version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: find_my_rice
      POSTGRES_PASSWORD: password
      POSTGRES_DB: find_my_rice_development
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/find_my_rice
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: find_my_rice
      POSTGRES_PASSWORD: password
      POSTGRES_DB: find_my_rice_development
